### ISSUE TITLE
Change Requests

### ISSUE THREAD

**Issue by cbl** [Astrotomic/laravel-fileable#1]
I have some improvement Ideas that I think would be great.

1. Changing `Concerns` folder name to `Traits`.

The `Concerns` folder are used by Laravel for traits that should not be used outside of the package/component, so *concerning* classes within the package/component. And `Traits` are meant to be used outside of the package. (Please correct me if I'm wrong)

2. Changing the `Fileable` trait name to `HasFiles`.

Renaming the trait to `HasFiles` has the benefit that no alias has to be created since the contract is named the same.

**Comment by Gummibeer** [comment]
There isn't a fully consistent rule about concerns in Laravel `\App\Eloquent\Concerns\Authorizable` for example.
And I use that namespace for all packages as it makes it clear that these are traits. I think that isn't worth a breaking release. And even if the renaming enforces a breaking release I would still want to keep the namespace part in case there are more traits in the future.

The `Fileable` trait renaming is a valid point and I would accept a PR.
